```{r}
library(tidyverse)
library(here)
library(dplyr)
library(terra)
library(sf)
library(countrycode)
#! janitor for clean names
library(janitor)
library(tmap)
library(tmaptools)
```

```{r}
# read the global gender inequality data

# time series 1990-2021
# column name e.g. gii_1990

# read the global gender inequality data ggi
ggi <- read_csv(here("prac4_data", "HDR21-22_Composite_indices_complete_time_series.csv"),
                locale = locale(encoding = "latin1"),
                na = " ", skip=0)
  #dplyr::select(contains("iso3"), contains("gii"), contains("country"))

# create Gender Inequality Index (value) == gii

# ! read_csv with here don't forget locale, na, skip

```
```{r}
# needs: create new column of difference in the
# inequality between 2010 and 2019
HDIcols<- ggi %>%
  # ! can always clean name first
  clean_names()%>%
  select(iso3, country, gii_2019, gii_2010)%>%
  mutate(difference=gii_2019-gii_2010)%>%
  # ! countrycode pkg can help to change country name
  # to country code
  mutate(iso_code=countrycode(country, origin = 'country.name', destination = 'iso2c'))%>%
  mutate(iso_code2=countrycode(iso3, origin = 'iso3c', destination = 'iso2c'))
  

```

```{r}
# read the spatial data of the world
world <- st_read(here("prac4_data", "World_Countries_(Generalized)", "World_Countries__Generalized_.shp"))
 

```

```{r}
# join the two data set
# ! sptail data is left (info to suit space)
join_HDI <- world %>%
  clean_names() %>%
  left_join(.,
            HDIcols,
            by = c("iso" = "iso_code"))


```

```{r}
# plot the map
# map the column "difference"
tmap_mode("plot")

# test the quick map
#join_HDI %>%
  #qtm(.,
      #fill = "difference")

  tm_shape(join_HDI) + 
  # map the column "difference"
  tm_polygons("difference",
              style="pretty",
              palette="Blues",
              midpoint=NA,
              alpha = 0.5) +
  tm_compass(position = c("left", "bottom"), type = "arrow") +
  tm_scale_bar(position = c("left", "bottom")) +
  tm_layout(title = "Difference in inequality between 2010 and 2019", 
            legend.position = c("right", "bottom"))

```

